services:
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend
      - db
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
